# Welcome to Jekyll!
#

# Site settings
title: Code For Kansas City
description: Kansas City locals helping Kansas City government and local organizations open their data and create meaningful tools
owner: Your Name # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/codeforkc
  github: https://github.com/codeforkansascity
  meetup: http://meetup.com/kcbrigade
  email: /contact/http://eepurl.com/7gbQP
  
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
